### ISSUE TITLE
Docker-image

### ISSUE THREAD

**Issue by krueuw** [gri38/django-joplin_vieweb#68]
It would be really nice if you could try this out without installing and configuring the many dependencies. a finished Docker image from a specialist could be the solution to be able to host it yourself and to operate behind the reverse proxy traffik :-) Letsencrypt can also take over.

**Comment by gri38** [comment]
Hi.
Good idea.
I'm not really aware about Docker, but I need to learn for other projects too.
I'll probably do... but not so soon...

**Comment by krueuw** [comment]
yes, I think the familiarization with Docker and a dockerfile makes it easier to maintain a project in the medium term, because many things are automated and the psychological hurdles are lower to try or change things :-)

**Comment by gri38** [comment]
done
