### ISSUE TITLE
Test with joppy 0.0.5

### ISSUE THREAD

**Issue by marph91** [gri38/django-joplin_vieweb#76]
Joppy should now support python 3.6 and 3.7. You can install from [source](https://github.com/marph91/joppy) or via `pip install joppy==0.0.5`.

**Comment by gri38** [comment]
Thanks a lot for your reactivity @marph91 
I'll test and let you know.

**Comment by gri38** [comment]
Fixed in [V1.17..0](https://github.com/gri38/django-joplin_vieweb/releases/tag/1.17.0)
